language: python

dist: xenial


before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg

matrix:
  include:
    - python: 2.7
      env:
       - TOX_ENV=py27
    - python: 3.7
      env:
        - TOX_ENV=py37
script: video_worker

script:
  - tox -e $TOX_ENV

after_success:
  - pip install -U codecov
  - codecov
