language: python

dist: xenial


before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg

install:
  - make requirements

# Note we currently run on python3.7 in production
python:
  - 3.7
  - 3.8

env:
  - TOX_ENV=testenv

script: video_worker

script:
  - tox -e $TOX_ENV

after_success:
  - pip install -U codecov
  - codecov
